<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        class Promise {
            constructor(executor) {
                this.state = "pending";
                this.value = undefined;
                this.reason = undefined;
                this.onResolvedCallbacks = [];
                this.onRejectedCallbacks = [];
                let resolve = (value) => {
                    if (this.state === "pending") {
                        this.state = "fulfilled";
                        this.value = value;
                        this.onResolvedCallbacks.forEach(fn => fn());
                    }
                }
                let reject = (reason) => {
                    if (this.state === "pending") {
                        this.state = "rejected";
                        this.reason = reason;
                        this.onRejectedCallbacks.forEach(fn => fn());
                    }
                }
                try {
                    executor(resolve, reject);
                } catch (err) {
                    reject(err);
                }
            }
            then(onFulfilled, onRejected) {
                // onFulfilled如果不是函数，就忽略onFulfilled，直接返回value
                onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
                // onRejected如果不是函数，就忽略onRejected，直接抛出错误
                onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };

                let p2 = new Promise((resolve, reject) => {
                    if (this.state === "fulfilled") {
                        // 异步
                        setTimeout(() => {
                            try {
                                let x = onFulfilled(this.value);
                                resolvePromise(p2, x, resolve, reject);
                            } catch (err) {
                                reject(err);
                            }
                        }, 0)
                    }
                    if (this.state === "rejected") {
                        // 异步
                        setTimeout(() => {
                            try {
                                let x = onRejected(this.reason);
                                resolvePromise(p2, x, resolve, reject);
                            } catch (err) {
                                reject(err);
                            }
                        }, 0)
                    }
                    if (this.state === "pending") {
                        this.onResolvedCallbacks.push(() => {
                            // 异步
                            setTimeout(() => {
                                try {
                                    let x = onFulfilled(this.value);
                                    resolvePromise(p2, x, resolve, reject);
                                } catch (err) {
                                    reject(err);
                                }
                            }, 0)
                        })
                        this.onRejectedCallbacks.push(() => {
                            // 异步
                            setTimeout(() => {
                                try {
                                    let x = onRejected(this.reason);
                                    resolvePromise(p2, x, resolve, reject);
                                } catch (err) {
                                    reject(err);
                                }
                            }, 0)
                        })
                    }
                })
                return p2
            }
        }
        function resolvePromise(promise2, x, resolve, reject) {
            // 循环引用报错
            if (x === promise2) {
                return reject(new TypeError("Chaining cycle detected for promise"))
            }
            // 防止多次调用
            let called;
            // x不是null 且x是对象或者函数
            if (x != null && (typeof x === 'object' || typeof x === 'function')) {
                try {
                    // A+规定，声明then = x的then方法
                    let then = x.then;
                    // 如果then是函数，就默认是promise了
                    if (typeof then === 'function') {
                        // 就让then执行 第一个参数是this   后面是成功的回调 和失败的回调
                        then.call(x, y => {
                            // 成功和失败只能调用一个
                            if (called) return;
                            called = true;
                            // resolve的结果依旧是promise 那就继续解析
                            resolvePromise(promise2, y, resolve, reject);
                        }, err => {
                            // 成功和失败只能调用一个
                            if (called) return;
                            called = true;
                            reject(err); // 失败就失败了
                        })
                    } else {
                        resolve(x); //直接成功即可
                    }
                } catch (err) {
                    // 也属于失败
                    if (called) return;
                    called = true;
                    // 取出then出错了就不要继续执行
                    reject(err);
                }
            } else {
                resolve(x);
            }
        }
        const p = new Promise((resolve, reject) => {
            resolve(500);
        })

        const p2 = p.then((data) => {
            console.log(data);
            return p2;
        })
        p2.then((res) => {
            console.log(res);
        }, err => {
            console.log(err);
        })
    </script>
</body>

</html>